# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2"

ANSIBLE_VERSION = "2.4.*"

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-16.04"

  config.vm.synced_folder "./", "/vagrant", type: "rsync",
    rsync__exclude: [
      ".git/", ".sbt/",
      "app-backend/.ensime/", "app-backend/.ensime_cache",
      "app-backend/.idea/", "app-backend/project/.ivy/",
      "app-backend/project/.boot/", "app-backend/project/.sbtboot/",
      "app-backend/**/target/",
      "deployment/ansible/roles/azavea*/"
    ]
  config.vm.synced_folder "~/.aws", "/home/vagrant/.aws"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.install = true
    ansible.install_mode = "pip_args_only"
    ansible.pip_args = "ansible==#{ANSIBLE_VERSION}"
    ansible.raw_arguments = ["--extra-vars",
                             "dev_user=#{ENV.fetch("USER", "vagrant")}"]
    ansible.playbook = "deployment/ansible/$name;format="norm"$-api.yml"
    ansible.galaxy_role_file = "deployment/ansible/roles.yml"
    ansible.galaxy_roles_path = "deployment/ansible/roles"
  end

  config.vm.provision "shell" do |s|
    s.inline = <<-SHELL
    if ! grep -q "cd /vagrant" "/home/vagrant/.bashrc"; then
      echo "cd /vagrant" >> "/home/vagrant/.bashrc"
    fi

    cd /vagrant
    su vagrant ./scripts/update
    SHELL
  end

  # API
  config.vm.network :forwarded_port, guest: $api_port$, host: $api_port$

end
